### ISSUE TITLE
ace vim mode and :w -> recompile

### ISSUE THREAD

**Issue by iosonofabio** [sharelatex/web-sharelatex#173] opened 2015-04-24 17:43 UTC
Hi!

I use the vim mode of ace and end up saving with :w quite often.

On Sharelatex, saving makes no sense but I'd like to get a better behaviour than

"TypeError: cm.save is not a function"

I'd suggest to link that to recompile, just like Ctrl+Enter, since that's the action expected at an edit break...

Note: I opened an issue on https://github.com/sharelatex/sharelatex/issues/303 which you probably want to close, since this is the correct repo. Sorry for that.

**Comment by khatchad** [comment] 2016-09-27 14:17
Dupe of #152?

**Closed** 2017-07-25 11:43 UTC
